# Generated by Django 4.2.2 on 2023-06-30 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_producto_arte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='tipo_consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.arte'),
        ),
    ]
